# Function for storing whole text of User Home
def user_home_text():
    text_lis = [
    "KisanTech",
    "Name",
    "Phone Number",
    "Status",
    "Farmer",
    "Location",
    "Ambala, Haryana",
    "Edit Profile",
    "Home",
    "Weather",
    "Work",
    "Blog",
    "Contact",
    "Kisan",
    "Tech",
    "WELL ROOTED TO NATURE",
    "OUR SPECIAL FEATURES",
    "HERE YOU WILL GET THE INFORMATION OF WEATHER OF YOUR LOCATION, FINANCIAL HELP AND FERTILIZERS SUITABLE FOR YOUR CROPS!!",
    "WEATHER FORECAST",
    "click here to know the climatic changes for the next seven days",
    "Financial help", 
    "Click here to get the benifit of amazing loan and insurance offers",
    "Shop Now", 
    "Click here to get the appropriate materials for your crop at best price",
    "Videos",
    "INFORMATIVE VIDEOS FOR YOU", 
    "Illustration",
    "Even the all-powerful Pointing has no control",
    "Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.",
    "Application", 
    "Even the all-powerful Pointing has no control",
    "Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.",
    "Web Design",
    "Even the all-powerful Pointing has no control",
    "Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind tet by the name of Lorem Ipsum decided to leave for the far World of Grammar.",
    "THANKS FOR YOUR VISIT",
    "HERE WE HAVE MORE FEATURES FOR YOU!!",
    "Financial Help", 
    "Click here for financial support. 'A good financial plan is a roadmap that shows us exactly how the choices we make today will affect our future.'",
    "Multiple Functions",
    "Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.",
    "Advanced Visualizations",
    "Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.",
    "Community and Supports",
    "Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.",
    "HELPFUL LINKS FOR YOU!!",
    "Click here to associate with - ",
    " PM-KISAN-SAMMAN-NIDHI-YOJANA",
    "Click here to know all details of - ",
    " CENTRAL-GOVERNMENT-SCHEMES",
    "DEVELOPERS",
    "PRO-CODERS",
    "Aaditya Singhal",
    "Abhay Dhiman",
    "Ayush Malik ",
    "Akshita Sharma",
    "CONTACT",
    "Copyright",
    "All rights reserved",
    "This template is made with",
    "by",
    "PRO-CODERS"
    ]

    return text_lis


# Function for storing whole text of Weather Page
def weather_text():
    text_lis = [
    "Weather",
    "Home",
    "Weather",
    "Work",
    "Blog",
    "Contact",
    "Weather ",
    "Max",
    "Min",
    "Visibility",
    "Wind",
    "Humidity",
    "DEVELOPERS",
    "PRO-CODERS",
    "Aaditya Singhal",
    "Abhay Dhiman",
    "Ayush Malik ",
    "Akshita Sharma",
    "CONTACT",
    "Copyright",
    "All rights reserved",
    "This template is made with",
    "by",
    "PRO-CODERS"
    ]

    return text_lis
