# Generated by Django 3.1 on 2020-09-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
